version: "3.9"

services:

  nginx:
    image: nginx:alpine
    container_name: my_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - mynet
    restart: unless-stopped


  app:
    image: node:20-alpine
    container_name: my_app
    working_dir: /app
    command: sh -c "npm install && node server.js"
    volumes:
      - ./app:/app
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - REDIS_HOST=redis
    depends_on:
      - postgres
      - redis
    networks:
      - mynet
    restart: unless-stopped


  postgres:
    image: postgres:16-alpine
    container_name: my_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynet
    restart: unless-stopped


  redis:
    image: redis:7-alpine
    container_name: my_redis
    command: redis-server --appendonly yes
    volumes:
      - redisdata:/data
    networks:
      - mynet
    restart: unless-stopped

networks:
  mynet:
    driver: bridge

volumes:
  pgdata:
  redisdata: